apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: babs-app
  labels:
    app: worker
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: worker
        tier: backend
    spec:
      containers:
        - name: worker
          image: babanila/worker:2.0
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: PGHOST
              value: "postgres"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database_name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database_user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database_password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
