apiVersion: v1
kind: Service
metadata:
  # The name is hardcoded (fixed) in server.js in result image
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
