apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: babs-app
  labels:
    app: result
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: result
        tier: frontend
    spec:
      containers:
        - name: result
          image: babanila/result:3.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PORT
              value: "80"
            - name: PG_HOST
              value: "db"
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: "postgres"
            - name: PG_PASSWORD
              value: "postgres"
            - name: PG_DATABASE
              value: "postgres"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
