apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: babs-app
  labels:
    app: result
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081  # Result on port 8081 -> NodePort 30081
      protocol: TCP
