apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: babs-app
  labels:
    app: vote-service
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
